all:
  hosts:
    node1:
      ansible_host: 10.2.52.202
      ip: 10.2.52.202
      access_ip: 10.2.52.202
    node2:
      ansible_host: 10.2.52.215
      ip: 10.2.52.215
      access_ip: 10.2.52.215
    node3:
      ansible_host: 10.2.52.214
      ip: 10.2.52.214
      access_ip: 10.2.52.214
    node4:
      ansible_host: 10.2.52.209
      ip: 10.2.52.209
      access_ip: 10.2.52.209
    node5:
      ansible_host: 10.2.52.218
      ip: 10.2.52.218
      access_ip: 10.2.52.218
    node6:
      ansible_host: 10.2.52.217
      ip: 10.2.52.217
      access_ip: 10.2.52.217
    node7:
      ansible_host: 10.2.52.155
      ip: 10.2.52.155
      access_ip: 10.2.52.155
    node8:
      ansible_host: 10.2.52.157
      ip: 10.2.52.157
      access_ip: 10.2.52.157
    node9:
      ansible_host: 10.2.52.158
      ip: 10.2.52.158
      access_ip: 10.2.52.158      
  children:
    kube-master:
      hosts:
        node1:
        node2:
        node6:
    kube-node:
      hosts:
        node3:
        node4:
        node5:
        node7:
        node8:
        node9:             
    etcd:
      hosts:
        node1:
        node2:
        node6:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
